### ISSUE TITLE
Add support for datasets with category combo configured

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-datacapture#39]

**Comment by ifoche** [comment]
User feedback:
Android does not appear to be properly handling retrieval of data with Attribute CatCombos. If two datasets are created containing the same values, one with an Attribute CatCombo and one without, then Data Capture should show completely different values for each one (ie the 'default' CatCombo option for the Data Set without an Attribute CatCombo, and the selected CatCombo option for the Data Set with an Attribute CatCombo).
This works correctly on the web, with different values being saved and retrieved. On Android, values saved under a specific CatCombo option in the first Data Set are then retrieved when the second Data Set (without CatCombos) is opened; in other words, instead of retrieving 'default' values, it retrieves a (random?) CatCombo option; any changes that are made are then saved as the 'default' CatCombo - meaning that if the erroneous Data Set is closed and re-opened, none of the values just entered show up (in other words, it saves them as default, then re-opens retrieving a specific CatCombo option).
To reproduce: load the two test Data Sets attached, which contain the same data elements, but with and without an Attribute CatCombo, and follow the steps above (doing web data entry into 'XX TEST - Monthly' against a specific CatCombo option, then opening the same period in 'XX TEST - Monthly + sections'). Note that the two key differences between these two Data Sets are that one has no sections and an Attribute CatCombo, while the other has sections and no Attribute CatCombo.

**Comment by xurxodev** [comment]
@ifoche I assign invalid label because after the tests seems a web API error. I have created the  issue in JIRA https://jira.dhis2.org/browse/DHIS2-1851
