### ISSUE TITLE
Sort order of data elements different on android and web

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-datacapture#43]
Order of data elements for category combinations is different in android vs web.
Example 1: Dataset Clinical Monitoring Checklist, org unit Ngelehun CHC. This is a dataset without sections and with a custom form. The order on the android is very different than the web.
For this same dataset, if you select 'Get PDF for data entry' (maintenance>datasets>rightclick) the data elements are aligned on the PDF in the same order as they appear on the android. If you remove the custom form from the web version, the order on the web matches the order on the android.
Another example dataset where there are differences: dataset ART monthly summary.

**Comment by idelcano** [comment]
@ifoche this is the correct behavior.
The custom forms is ignored in android.

**Comment by ifoche** [comment]
you're right, closing the issue
