### ISSUE TITLE
Cached data produceds silent sync failures

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-datacapture#86]
It looks like any data that is cached on the device is causing problems between versions. I wiped all data from the cache, un-installed last version, installed the official Play Store version of the Data Capture app, successfully captured and synched some data to Previous2, and then un-installed the Play Store version without removing the cached data. I then installed the new last version over the top of this existing data, and tried capturing further data for the same Data Set.
The result was that all attempts at synching would fail silently - the synch would run as normal, but no entry would be added to the synch logs. Any changes on the device wouldn't appear on the server, and any changes on the server wouldn't appear on the device. (Since this cached data clearly causes problems, it wouldn't surprise me if that's also what caused this ticket's crash when I first upgraded - my first step was to then clear the app's cached data.) However, as soon as I cleared the app's cached data, everything synched properly.

**Comment by idelcano** [comment]
@manuelplazaspalacio I think this problem was solved after merge the changes in the issue #105 (allowBackup=false)
