### ISSUE TITLE
Find the system limits

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-datacapture#92]
Recommendations in terms of memory & minimum Amazon instance required

**Comment by tokland** [comment]
Check https://github.com/EyeSeeTea/ESTools/wiki/Dhis2-https://github.com/EyeSeeTea/ESTools/wiki/Dhis2-Benchmarking#dhis2androiddatacapture

Some notes:

- Performance is similar across dhis2 versions (2.25, 2.26, 2.27), slightly better for 2.27.
- An increase on CPU should reduce roughly proportionally the mean times, but more tests on real scenarios should be made.
- How many users can the instance manage? This app loads less the server than dashboards, but the responses time for > 50 users are already quite high (75secs for initial sync).
