### ISSUE TITLE
Avoid keyboard from obscuring the Save button

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-datacapture#95]
To avoid the need of going to the bottom of the dataset in order to save it (some people goes down and then review the dataset by going up again), add another save button at the top of the screen

**Comment by idelcano** [comment]
@ifoche I think this feature does not make sense in the current version of the app, the save button is always visible. What do you think?
 
![dataset](https://user-images.githubusercontent.com/5302538/29693416-bcb46662-8935-11e7-8f62-0fdb6edd2d62.png)

**Comment by ifoche** [comment]
BTW, I changed the issue title accordingly
