### ISSUE TITLE
If dataSet has already been approved open it only in read-only mode

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-datacapture#97]
Use this endpoint to check approval state:
https://play.dhis2.org/android-current/api/dataApprovals?ds=BfMAe6Itzgt&pe=201706&ou=O6uvpzGd5pu

Please look at the documentation [in section 1.26](https://docs.dhis2.org/2.24/en/developer/html/ch01s26.html). The logic must be:
- If dataSet has expired (the expiry date is over) or the dataSet has already been approved: open in readOnly mode
- Else open in normal mode

**Comment by idelcano** [comment]
@ifoche i don`t know how check the expired days. 
The datset have a expireDays field, and i added it into the app to open the dataset as read only if the dataSet is over it, but i don't see how can check it.

I need know if a dataset is over the expire days, what need i check against the "expired days" field?  the creation date?, the period(i think can`t be the period)?

In this link the expired days is explained but i don't understand how i can verify this..
https://docs.dhis2.org/2.22/en/user/html/ch06.html

I had other problem with this issue.
When i tried query against the server the data approval only works with the "mortality < 5 years" dataset, when i tried with others the server response was: 
httpStatus: "Conflict",
httpStatusCode: 409,
status: "ERROR",
message: "Data set does not have an approval workflow: BfMAe6Itzgt"


And other problem... the dataset pBOMPrpg1QX is working:
https://play.dhis2.org/android-previous1/api/dataApprovals?ds=pBOMPrpg1QX&pe=201712&ou=O6uvpzGd5pu
but.. when i tried to change the status to Approved to test this dataset the server response was a server conflict, 
i have followed the instructions and send the follow json (Post):
{
  "ds": [
    "pBOMPrpg1QX"
  ],
  "pe": [
    "201709"
  ],
  "approvals": [{
      "ou": "O6uvpzGd5pu"
    }]
}


to the url : https://play.dhis2.org/android-previous1/api/24/dataApprovals/approvals
And the respone was...
{
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "ERROR"
}

**Comment by manuelplazaspalacio** [comment]
Nos vemos mañana t
